# Aula - Manipulação Estrutural com Pandas

Manipulação estrutural diz respeito à modificação da estrutura de uma dataframe. Isso é realizado na etapa de ETL.

**Um dataframe é composto de:** <span style="color: red">Colunas</span> e linhas.

**A estrutura de uma dataframe é determinada pela configuração das suas <span style="color: red">colunas</span>.**
- Quais colunas fazem parte do dataframe?
- Quais os tipos dessas colunas?
- Quais os nomes dessas colunas?

**A manipulação de estrutura é:**
- Definir quais colunas farão parte do df
- Remover colunas de um df
- Criar novas colunas
- Renomear uma coluna existente
- Alterar o tipo de uma coluna existente
- Modificar o index de um dataframe

### Importações usadas nesta aula

In [ ]:
pip install pandas

Requirement already satisfied: pandas in c:\users\paulo\appdata\local\programs\python\python312\lib\site-packages (2.2.0)Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: numpy<2,>=1.26.0 in c:\users\paulo\appdata\local\programs\python\python312\lib\site-packages (from pandas) (1.26.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\paulo\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\paulo\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\paulo\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2023.4)
Requirement already satisfied: six>=1.5 in c:\users\paulo\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [ ]:
import pandas as pd # importando biblioteca Pandas

### Carregando o Dataframe

In [ ]:
df = pd.read_excel("./resultados.xlsx") # carregando base de dados
df[[
    "Edition", "Round", "Date", "Home Club", "Away Club", "Home Score", "AwayScore" # criando Novas colunas
]] = df["Edition,Round,Date,Home Club,Away Club,Home Score,AwayScore"].str.split(",", expand=True)

df

,"Edition,Round,Date,Home Club,Away Club,Home Score,AwayScore",Edition,Round,Date,Home Club,Away Club,Home Score,AwayScore
0,"2023,Final,4/11/2023,Fluminense FC,Boca Junior...",2023,Final,4/11/2023,Fluminense FC,Boca Juniors,2,1
1,"2023,Semifinal,6/10/2023,Palmeiras,Boca Junior...",2023,Semifinal,6/10/2023,Palmeiras,Boca Juniors,1,1
2,"2023,Semifinal,5/10/2023,Internacional,Flumine...",2023,Semifinal,5/10/2023,Internacional,Fluminense FC,1,2
3,"2023,Semifinal,29/09/2023,Boca Juniors,Palmeir...",2023,Semifinal,29/09/2023,Boca Juniors,Palmeiras,0,0
4,"2023,Semifinal,28/09/2023,Fluminense FC,Intern...",2023,Semifinal,28/09/2023,Fluminense FC,Internacional,2,2
...,...,...,...,...,...,...,...,...
1816,"2013,Qualifying Match,24/01/2013,SÃ£o Paulo,Bo...",2013,Qualifying Match,24/01/2013,SÃ£o Paulo,BolÃ­var,5,0
1817,"2013,Qualifying Match,24/01/2013,LDU de Quito,...",2013,Qualifying Match,24/01/2013,LDU de Quito,GrÃªmio,1,0
1818,"2013,Qualifying Match,24/01/2013,Defensor Spor...",2013,Qualifying Match,24/01/2013,Defensor Sporting,Olimpia,0,0
1819,"2013,Qualifying Match,23/01/2013,Tigre,Deporti...",2013,Qualifying Match,23/01/2013,Tigre,Deportivo AnzoÃ¡tegui,2,1
1820,"2013,Qualifying Match,23/01/2013,LeÃ³n,Deporte...",2013,Qualifying Match,23/01/2013,LeÃ³n,Deportes Iquique,1,1

### Definir quais colunas farão parte do df

In [ ]:
df_select_columns = df
df_select_columns = df[["Edition", "Date", "Home Club", "Away Club", "Home Score", "AwayScore"]] # definindo as colunas que fara parte da base de dados
df_select_columns

,Edition,Date,Home Club,Away Club,Home Score,AwayScore
0,2023,4/11/2023,Fluminense FC,Boca Juniors,2,1
1,2023,6/10/2023,Palmeiras,Boca Juniors,1,1
2,2023,5/10/2023,Internacional,Fluminense FC,1,2
3,2023,29/09/2023,Boca Juniors,Palmeiras,0,0
4,2023,28/09/2023,Fluminense FC,Internacional,2,2
...,...,...,...,...,...,...
1816,2013,24/01/2013,SÃ£o Paulo,BolÃ­var,5,0
1817,2013,24/01/2013,LDU de Quito,GrÃªmio,1,0
1818,2013,24/01/2013,Defensor Sporting,Olimpia,0,0
1819,2013,23/01/2013,Tigre,Deportivo AnzoÃ¡tegui,2,1
1820,2013,23/01/2013,LeÃ³n,Deportes Iquique,1,1

### Removendo colunas de um dataframe

In [ ]:
df_remove_columns = df_select_columns
df_remove_columns = df_remove_columns.drop(columns=["Edition"], axis=1) # removendo coluna da base de dados
df_remove_columns

,Date,Home Club,Away Club,Home Score,AwayScore
0,4/11/2023,Fluminense FC,Boca Juniors,2,1
1,6/10/2023,Palmeiras,Boca Juniors,1,1
2,5/10/2023,Internacional,Fluminense FC,1,2
3,29/09/2023,Boca Juniors,Palmeiras,0,0
4,28/09/2023,Fluminense FC,Internacional,2,2
...,...,...,...,...,...
1816,24/01/2013,SÃ£o Paulo,BolÃ­var,5,0
1817,24/01/2013,LDU de Quito,GrÃªmio,1,0
1818,24/01/2013,Defensor Sporting,Olimpia,0,0
1819,23/01/2013,Tigre,Deportivo AnzoÃ¡tegui,2,1
1820,23/01/2013,LeÃ³n,Deportes Iquique,1,1

### Adicionando novas colunas ao df

In [ ]:
df_add_columns = df_remove_columns
df_add_columns["Total Gols"] = df_add_columns["Home Score"] + df_add_columns["AwayScore"] # adicionando nova coluna na base de dados

df_add_columns

,Date,Home Club,Away Club,Home Score,AwayScore,Total Gols
0,4/11/2023,Fluminense FC,Boca Juniors,2,1,21
1,6/10/2023,Palmeiras,Boca Juniors,1,1,11
2,5/10/2023,Internacional,Fluminense FC,1,2,12
3,29/09/2023,Boca Juniors,Palmeiras,0,0,00
4,28/09/2023,Fluminense FC,Internacional,2,2,22
...,...,...,...,...,...,...
1816,24/01/2013,SÃ£o Paulo,BolÃ­var,5,0,50
1817,24/01/2013,LDU de Quito,GrÃªmio,1,0,10
1818,24/01/2013,Defensor Sporting,Olimpia,0,0,00
1819,23/01/2013,Tigre,Deportivo AnzoÃ¡tegui,2,1,21
1820,23/01/2013,LeÃ³n,Deportes Iquique,1,1,11

### Alterando o tipo de uma coluna existente

In [ ]:
df_types = df_add_columns

df_types["Home Score"] = df_types["Home Score"].astype(float) # alterando a tipagem de uma coluna
df_types["AwayScore"] = df_types["AwayScore"].astype(float)

df_types["Total Gols"] = df_types["Home Score"] + df_types["AwayScore"]
df_types

,Date,Home Club,Away Club,Home Score,AwayScore,Total Gols
0,4/11/2023,Fluminense FC,Boca Juniors,2.0,1.0,3.0
1,6/10/2023,Palmeiras,Boca Juniors,1.0,1.0,2.0
2,5/10/2023,Internacional,Fluminense FC,1.0,2.0,3.0
3,29/09/2023,Boca Juniors,Palmeiras,0.0,0.0,0.0
4,28/09/2023,Fluminense FC,Internacional,2.0,2.0,4.0
...,...,...,...,...,...,...
1816,24/01/2013,SÃ£o Paulo,BolÃ­var,5.0,0.0,5.0
1817,24/01/2013,LDU de Quito,GrÃªmio,1.0,0.0,1.0
1818,24/01/2013,Defensor Sporting,Olimpia,0.0,0.0,0.0
1819,23/01/2013,Tigre,Deportivo AnzoÃ¡tegui,2.0,1.0,3.0
1820,23/01/2013,LeÃ³n,Deportes Iquique,1.0,1.0,2.0

### Renomeando colunas de um dataframe

In [ ]:
df_rename = df_types
df_rename = df_rename.rename( # Renomeando Colunas da base de dados
    columns={
        "Date": "partida_data",
        "Home Club":  "time_mandante_nome",
        "Away Club":  "time_visitante_nome",
        "Home Score":  "time_mandante_gols",
        "AwayScore":  "time_visitante_gols",
        "Total Gols":  "partida_gols",
    }
)

df_rename

,partida_data,time_mandante_nome,time_visitante_nome,time_mandante_gols,time_visitante_gols,partida_gols
0,4/11/2023,Fluminense FC,Boca Juniors,2.0,1.0,3.0
1,6/10/2023,Palmeiras,Boca Juniors,1.0,1.0,2.0
2,5/10/2023,Internacional,Fluminense FC,1.0,2.0,3.0
3,29/09/2023,Boca Juniors,Palmeiras,0.0,0.0,0.0
4,28/09/2023,Fluminense FC,Internacional,2.0,2.0,4.0
...,...,...,...,...,...,...
1816,24/01/2013,SÃ£o Paulo,BolÃ­var,5.0,0.0,5.0
1817,24/01/2013,LDU de Quito,GrÃªmio,1.0,0.0,1.0
1818,24/01/2013,Defensor Sporting,Olimpia,0.0,0.0,0.0
1819,23/01/2013,Tigre,Deportivo AnzoÃ¡tegui,2.0,1.0,3.0
1820,23/01/2013,LeÃ³n,Deportes Iquique,1.0,1.0,2.0

### Modificando o index de um df

In [ ]:
df_index = df_rename
df_index = df_index["partida_gols"] # Ele funciona exatamente como as chaves de um dicionário do Python , permitindo que você encontre, alinhe e manipule dados de forma rápida e eficiente.
df_index = df_index.reset_index()
df_index = df_index.set_index("index")
df_index

       partida_gols
index
0               3.0
1               2.0
2               3.0
3               0.0
4               4.0
...             ...
1816            5.0
1817            1.0
1818            0.0
1819            3.0
1820            2.0

[1821 rows x 1 columns]